name: ai_assistant
description: "A AI Assistant (ChatBot, Image Genrator, & Language Translator) App Based on ChatGPT."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # iOS Styled Icons
  cupertino_icons: ^1.0.8

  # For Using Lottie Animations
  lottie: ^3.3.1

  # For Hive Database
  hive: ^4.0.0-dev.2
  isar_flutter_libs: ^4.0.0-dev.13

  # For Accessing Storage Path
  path_provider: ^2.1.0

  # For State Management
  get: ^4.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Encourages Good Practices
  flutter_lints: ^5.0.0

  # For Changing App Icon
  icons_launcher: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
